package com.openclassrooms.realestatemanager.domain.realEstate

import androidx.room.*
import com.openclassrooms.realestatemanager.data.local.model.RealEstateEntity
import com.openclassrooms.realestatemanager.data.local.model.RealEstatePhotoEntity
import com.openclassrooms.realestatemanager.data.local.model.RealEstateWithPhotos
import kotlinx.coroutines.flow.Flow

interface RealEstateRepository {

    suspend fun insertRealEstate(realEstateEntity: RealEstateEntity, onRealEstateInserted: (Long) -> Unit): Long

    suspend fun updateRealEstate(realEstateEntity: RealEstateEntity)

    suspend fun deleteRealEstate(realEstateId: Int)

    fun getRealEstateById(realEstateId: Int) : Flow<RealEstateWithPhotos>

    suspend fun insertRealEstatePhoto(realEstatePhotoEntity: RealEstatePhotoEntity)

    fun updateRealEstateIdOfPhotoEntity(autoGeneratedPhotoId: Long, realEstateEntityId: Int)

    fun deleteRealEstatePhoto(realEstatePhotoEntity: RealEstatePhotoEntity)

    fun getRealEstatesWithPhotos(): Flow<List<RealEstateWithPhotos>>



}

