package com.openclassrooms.realestatemanager.data.local.dao

import android.database.Cursor
import androidx.room.*
import com.openclassrooms.realestatemanager.data.local.model.RealEstateEntity
import com.openclassrooms.realestatemanager.data.local.model.RealEstatePhotoEntity
import com.openclassrooms.realestatemanager.data.local.model.RealEstateWithPhotos
import kotlinx.coroutines.flow.Flow

@Dao
interface RealEstateDao {

    @Insert(onConflict = OnConflictStrategy.REPLACE)
    suspend fun insertRealEstate(realEstateEntity: RealEstateEntity) : Long

    @Update
    suspend fun updateRealEstate(realEstateEntity: RealEstateEntity)

    @Query("DELETE FROM realEstates WHERE realEstateId = :realEstateId")
    suspend fun deleteRealEstate(realEstateId: Int)

    @Query("SELECT * FROM realEstates")
    fun getAllRealEstates() : Flow<List<RealEstateEntity>>

    @Insert(onConflict = OnConflictStrategy.REPLACE)
    suspend fun insertRealEstatePhoto(realEstatePhotoEntity: RealEstatePhotoEntity)

    @Delete
    fun deleteRealEstatePhoto(realEstatePhotoEntity: RealEstatePhotoEntity)

    @Transaction
    @Query("SELECT * FROM realEstates WHERE realEstateId = :realEstateId")
    fun getRealEstateWithPhotosById(realEstateId: Int) : Flow<RealEstateWithPhotos>

    @Transaction
    @Query("SELECT * FROM realEstates")
    fun getRealEstatesWithPhotos(): Flow<List<RealEstateWithPhotos>>

    @Query("UPDATE realEstatePhotos SET realEstateIdOfPhoto = :realEstateEntityId WHERE photoId = :autoGeneratedPhotoId")
    fun updateRealEstatePhotoId(autoGeneratedPhotoId: Long, realEstateEntityId: Int)

    // Content Provider methods
    @Query("SELECT * FROM realEstates")
    fun getAllRealEstatesAsCursor() : Cursor

    @Query("DELETE FROM realEstatePhotos")
    fun nukeRealEstatePhotosTable()

    @Query("DELETE FROM realEstates")
    fun nukeRealEstateTable()

    @Insert
    fun insertRealEstateNoReturn(realEstateEntity: RealEstateEntity)

}